### ISSUE TITLE
Segmentation fault during execution

### ISSUE THREAD

**Issue by ChristosMatzoros** [mgawan/ADEPT#25]
Hello,

Inside driver::kernel_launch at driver.cpp, should this for loop go up to query_seqs.size()? It seems that there are cases we are trying to access a position on offset_que, that doesn't exist. Maybe you need the iterations to go up to batch_size?

https://github.com/mgawan/ADEPT/blob/ed08b424aa179ffc25fd75a22976f77775deef92/adept/driver.cpp#L115

**Comment by mgawan** [comment]
Hi,
yes that is right, I just fixed it. Thanks for pointing out. 

-Muaaz
